# Generated by Django 4.0.6 on 2022-07-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='img',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accessory', models.CharField(choices=[('charger', 'Phone charger with cable'), ('phones', 'Headphones'), ('case', 'A hard plastic phone case'), ('screenprotector', 'A stick-on screen protector to prevent scratches')], default='charger', max_length=25)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.phone')),
            ],
        ),
    ]
