# Generated by Django 4.0.6 on 2022-07-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_cat_accessory_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='accessory',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='date',
            field=models.DateField(verbose_name='Date purchased'),
        ),
    ]
