# Generated by Django 4.0.6 on 2022-07-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_band_alter_accessory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='bands',
            field=models.ManyToManyField(to='main_app.band'),
        ),
    ]
